<?php
/**
 * Copyright since 2023 Floa
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Academic Free License (AFL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/AFL-3.0
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to tech@202-ecommerce.com so we can send you a copy immediately.
 *
 * @author 202 ecommerce <tech@202-ecommerce.com>
 * @copyright 2023 Floa
 * @license   https://opensource.org/licenses/AFL-3.0  Academic Free License (AFL 3.0)
 */
?>
<?php
/**
 * @var $block \FLOA\Payment\Block\Product\Widget
 */
?>
<?php if ($block->isEnabled()) : ?>
    <div data-floa-offers></div>
    <script type="text/x-magento-init">
        {
            "*": {
                "floaWidgetInitializer" : {
                    "floapay" : {
                        "url_images" : "<?= $block->escapeHtml($block->getImagesPath()) ?>",
                        "url_product" : "<?= $block->escapeHtml($block->getOfferUrl()) ?>",
                        "url_cgv" : "<?= $block->escapeHtml($block->getCgvUrl()) ?>",
                        "country_code" : "<?= $block->escapeHtml($block->getCountryCode()) ?>",
                        "language_context" : "<?= $block->escapeHtml($block->getLanguageContext()) ?>",
                        "currency_sign" : "<?= $block->escapeHtml($block->getCurrendySign()) ?>",
                        "translations" : {
                            "without_fees" : "<?= $block->escapeHtml(__('without fees')) ?>",
                            "pay_in" : "<?= $block->escapeHtml(__('Pay in')) ?>",
                            "your_payment_in" : "<?= $block->escapeHtml(__('Your payment in several time')) ?>",
                            "for_an_amount_of" : "<?= $block->escapeHtml(__('for an amount of')) ?>",
                            "for_this_purchase" : "<?= $block->escapeHtml(__('For this purchase, you can pay in :')) ?>",
                            "today" : "<?= $block->escapeHtml(__('Today')) ?>",
                            "total" : "<?= $block->escapeHtml(__('Total:')) ?>",
                            "with_fees" : "<?= $block->escapeHtml(__('Including fees:')) ?>",
                            "how_it_works" : "<?= $block->escapeHtml(__('How it works ?')) ?>",
                            "checkout_choose_floa" : "<?= $block->escapeHtml(__('At checkout choose FLOA')) ?>",
                            "enter_bank_details" : "<?= $block->escapeHtml(__('Enter your bank details on the secure FLOA platform')) ?>",
                            "et_voila" : "<?= $block->escapeHtml(__("And that's it. As easy as paying cash.")) ?>",
                            "immediate_response" : "<?= $block->escapeHtml(__('You get an immediate response.')) ?>",
                            "conditions_acceptance" : "<?= $block->escapeHtml(__('Subject to acceptance by FLOA. You have a withdrawal period.')) ?>",
                            "consult_the" : "<?= $block->escapeHtml(__('Consult the')) ?>",
                            "conditions_here" : "<?= $block->escapeHtml(__('conditions here')) ?>",
                            "paylater" : "<?= $block->escapeHtml(__('PAYLATER')) ?>"
                        },
                        "offers" : [],
                        "selectedOffer" : null,
                        "type" : "product"
                    }
                },
                "floaProduct" : {}
            }
        }
    </script>
<?php endif; ?>